Docker Image with Clojure tools.deps and vulcan

Provides the following utilities for use in Continuous integrations
and Git Release workflows

- openjre-8
- Clojure CLI
- vulcan - [[https://github.com/omnyway-labs/vulcan]] for running clojure
  tests using selectors, generate release semver tag

  #+BEGIN_SRC sh
  vulcan test -s unit
  vulcan next-tag
  #+END_SRC
- github-release


* Usage

To build:

#+BEGIN_SRC sh
make
docker run --name my-clojure-cli omnyway/vulcan -d
#+END_SRC

Or pull from dockerhub

#+BEGIN_SRC sh
docker pull omnyway/vulcan:latest
# or a sepcific version
docker pull omnyway/vulcan:0.1.3
#+END_SRC


* License - Apache 2.0

Copyright 2019 Omnyway Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

[[http://www.apache.org/licenses/LICENSE-2.0]]

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
